name: CI Pipeline

# Triggers the workflow on pushes to the main branch or pull requests.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the build.

    steps:
      # Step 1: Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"  # Set the Python version (adjust if necessary).

      # Step 3: Install dependencies from the requirements.txt file.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run linting using flake8.
      - name: Run linting
        run: |
          pip install black
          black .  # Lint the entire project to ensure code quality.

      # Step 5: Run tests using pytest.
      - name: Run tests
        run: |
          pip install pytest
          pytest  # Run all the tests in the project.
