name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          pip install black
          black .

      # Step to check if any test files exist
      - name: Check if test files exist
        id: test_check
        run: |
          if [ -z "$(find . -name 'test_*.py')" ]; then
            echo "No test files found, skipping pytest."
            echo "run_tests=false" >> $GITHUB_ENV
          else
            echo "Test files found, running pytest."
            echo "run_tests=true" >> $GITHUB_ENV
          fi

      # Step to run tests, only if test files exist
      - name: Run tests
        if: env.run_tests == 'true'
        run: |
          pip install pytest
          pytest
